#   MIT License
#
#   Copyright(c) 2017-2018 Ilia Kosenkov [ilia.kosenkov.at.gm@gmail.com]
#
#   Permission is hereby granted, free of charge, to any person obtaining a copy
#   of this software and associated documentation files(the "Software"), to deal
#   in the Software without restriction, including without limitation the rights
#   to use, copy, modify, merge, publish, distribute, sublicense, and / or sell
#   copies of the Software, and to permit persons to whom the Software is
#   furnished to do so, subject to the following conditions:
#
#   The above copyright notice and this permission
#   notice shall be included in all
#   copies or substantial portions of the Software.
#
#   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#   IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
#   DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#   TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH
#   THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

SuppressNotes <- function(args) {
    for (var in args) {
        assign(var, NULL, envir = .GlobalEnv)
    }
}

SuppressNotes(".")


#' @importFrom stringr str_length
Tools.String.IndexOfChar = function(string, charPattern)
{
  #require(stringr)
  
  n = str_length(string)
  
  for (i in 1:n)
  {
    if (substr(string, i,i) == substr(charPattern, 1, 1))
      return(i)
  }
  return (-1)
}

Tools.Interpolate = function(x, args, vals)
{
  for (i in 1:(length(args)-1))
  {
    if ((x >= args[i]) & (x <= args[i+1]))
    {
      return(vals[i] + (vals[i+1] - vals[i]) * (x-args[i])/(args[i+1] - args[i]))
    }
  }
  
  return (NA)
}

Tools.AverageAndScatter = function(x, dx, limits = c(0.16, 0.84), nRuns = 1000, nUpd = 5, nSample = 10000) 
{
    #require(rjags)
    
    n = min(length(x), length(dx))
    x = x[1:n]
    dx = dx[1:n]
    jagsModel = "
    model
    {
        mean ~ dunif(lower, upper)
        
        for(i in 1:length(obsX))
        {
            obsX[i] ~ dnorm(mean, 1.0/ (obsdX[i]^2))
        }
    }
    "

    meanEst = mean(x)
    size = max(x + dx) - min(x-dx)
    lower = meanEst - size
    upper = meanEst + size

    initials = list("lower" = lower, "upper" = upper, "obsX" = x, "obsdX" = dx)

    logConnection = textConnection(NULL, open = "w")

    modelText = textConnection(jagsModel)
    
    sink(logConnection)

    model = jags.model(modelText, initials, n.chains = 1, n.adapt = nRuns)
    for (i in 1:ifelse(nUpd < 1, 1, nUpd))
    {
        update(model, nRuns, quiet = TRUE)
    }

    result = coda.samples(model, "mean", nSample, thin = 10)[[1]]

    mean = mean(result)
    sigmas = quantile(result, limits)
    close.connection(modelText)
    sink()
    
    return (list("Mean" = mean, "Limits" = sigmas))
}

#' @title JointDistributionContours
#' @param x First variable.
#' @param y Second variable.
#' @param prob Vector of probabilities in (0, 1).
#' @param n Size of the \code{MASS::kde2d} estimator's grid.
#' @return List of contours, one per each probability.
#' @importFrom grDevices contourLines
#' @importFrom purrr map map_dbl map2
#' @importFrom MASS kde2d
JointDistributionContours <- function(x, y, prob, n = 30) {
    # Calculates contours for a given 2D distribution (pairs of [x_i, y_i])
    # and given probabilities (vectorized over latter).
    # Args :
    #   x    : x coordinates of sampled distribution points
    #   y    : y coordinates of sampled distribution points
    #   prob : Vector of probabilities (e.g. c(0.5, 0.68, 0.95, 0.995)).
    #   n    : The number of points used in kernel density estimator
    #   (MASS::kde2d).
    #          THe larger n the more detailed estimation is
    #    and the more time it takes.
    # Returns: List of contours as generated by contourLines()

    if (!is.numeric(x) || !is.numeric(y))
        stop("x and y should be numeric.")

    if (length(x) != length(y))
        stop("x and y should be of the same length.")

    if (!is.numeric(prob) || prob < 0 || prob > 1)
        stop("prob should be a number from [0, 1] range.")

    if (!is.numeric(n) || n <= 1)
        stop("n should be a positive number at least greater than 1.")

    # Depends on MASS package
    #require(MASS)
    # Calculates 2D density
    dens <- kde2d(x, y, n = n)

    # Aranges values in ascending order
    Z <- sort(dens$z)
    # Bin size in x and y directions
    dx <- diff(dens$x[1:2])
    dy <- diff(dens$y[1:2])

    # Returns all cumulative sums:
    # z1; z1+z2; ...; z1+z2+z3+...zN
    # Times 2D bin size
    CZ <- cumsum(Z) * dx * dy

    # For each prob gives Z
    #levels <- sapply(prob, function(x)
    #{
        #approx(CZ, Z, xout = 1 - x)$y
    #})

    levels <- map(prob, ~approx(CZ, Z, xout = 1 - .x)$y)


    # Generates contour lines at appropriate levels
    cntrs <- contourLines(dens, levels = levels)

    ordInds <- cntrs %>%
        map_dbl(extract2, "level") %>%
        order

    cntrs <- cntrs %>%
        map2(ordInds, function(cnt, ind) {
            cnt$prob <- prob[ind]
            return (cnt)
        })

    return(cntrs)
}

Tools.GetSigma = function(x)
{
    return(mean(x$Mean - x$Limits[[1]], x$Limits[[2]] - x$Mean))
}

Tools.Assign = function(var, env = .GlobalEnv)
{
    name = deparse(substitute(var))
    
    assign(name, var, envir = env)
}

Tools.Cart2Pol = function(x, ...) {
    args = list(...)
    if (length(args) == 1) {
        y = args[[1]]
    }
    else {
       
        y = x[[2]]
        x = x[[1]]
    }

    return(list("r" = sqrt(x^2+ y^2), "a" = atan2(y, x)))
}

Tools.Pol2Cart = function(r, a) {
    return(list("x" = r * cos (a), "y" = r * sin (a)))
}

Tools.Norm = function(x) {
    return (sqrt(sum(x^2)))
}

#' @title FancyStep
#' @param range The range within which the ticks are placed.
#' @param n Approximate number of desired ticks.
#' @param modifier Preferred tick placements/
#' @return Returns the size of the step.
#' @import dplyr
#' @importFrom magrittr multiply_by raise_to_power subtract equals
#' @export
FancyStep <- function(range,
    n = 6, modifier = c(1, 2.5, 5)) {

    modifier <- c(0.1 * modifier, modifier)

    # Gets the smallest base_10 step
    largeSteps <- range %>%
        diff %>% abs %>% log10 %>% floor %>% raise(10)

    # Calculates the number of intervals within range
    # for each modifer and selects the ones
    # that produce the closest to n amount of breaks.
    # If there are multuple matches, selects the smallest step
    # or largest number of breaks
    modInd <- largeSteps %>%
        multiply_by(modifier) %>%
        raise_to_power(-1) %>%
        multiply_by(range %>% diff %>% abs) %>%
        subtract(n) %>%
        abs %>%
        equals(min(.)) %>%
        which

    largeSteps * modifier[modInd] %>% min
}

#' @title GenerateLog10Breaks
#' @param ylim Axis limit.
#' @return log10 breaks.
#' @importFrom magrittr is_weakly_less_than extract2 multiply_by add
#' @import dplyr
#' @export
GenerateLog10Breaks <- function(ylim) {

    if (ylim %>% log10 %>% diff %>% is_weakly_less_than(1)) {
        mult <- ylim %>% min %>% Log10Floor
        yInt <- ylim / mult

        lStep <- yInt %>% FancyStep(4)
        sStep <- 0.1 * lStep

        yRng <- yInt %>% RoundIntervalTo(lStep)

        breaks <- list(
            Large = seq(yRng[1], yRng[2], by = lStep),
            Small = seq(yRng[1], yRng[2], by = sStep))

        inds <- Intersect(breaks$Large, breaks$Small, tol = 0.5 * sStep) %>%
            extract2(2)

        breaks$Small <- breaks$Small[setdiff(1:length(breaks$Small), inds)]

        breaks <- breaks %>%
            lapply(Within, range = yInt) %>%
            lapply(multiply_by, mult)

    } else {

        breaks <- ylim %>% log10 %>%
        GenerateBreaks(largeStep = 1,
            ticks = log10(1:9), op = add)

        breaks$Large <- breaks$Large %>%
            lapply(function(x)
                log10(c(0.2, 0.5, 1, 2, 5)) + x) %>%
            unlist %>%
            unique %>%
            Within(range = log10(ylim))

        inds <- Intersect(breaks$Large, breaks$Small, tol = 1e-4)[[2]]

        breaks$Small <- breaks$Small[setdiff(1:length(breaks$Small), inds)]

        breaks <- breaks %>%
            lapply(Within, range = log10(ylim)) %>%
            sapply(raise, 10)
    }

    return(breaks)
}

#' @title Clamp
#' @param ... Parameter.
#' @return Clamped numerics.
#' @export
Clamp <- function(...) {
    UseMethod("Clamp")
}

#' @title Clamp.numeric
#' @param ... Input parameters.
#' @return Clamps vector.
#' @export
Clamp.numeric <- function(...) {
    args <- list(...)
    x <- args[[1]]
    lower <- args[[2]]
    upper <- args[[3]]
    if (!missing(lower))
        x[x < lower] <- lower
    if (!missing(upper))
        x[x > upper] <- upper

    return(x)
}


#' @title Expand
#' @param x Input interval.
#' @param factor How large the expansion is.
#' 1 corresponds to 100\% increase in size.
#' @param direction In which way to expand.
#' @return Expanded interval.
#' @export
Expand <- function(x, factor = 1, direction = c(1, 1)) {
    # Expands provided interval x factor times,
    # preserving the center of the interval
    # Args :
    #   x      : input interval
    #   factor : expanding factor
    # Returns :
    #   Expanded interval

    center <- mean(x)

    halfSize <- (diff(x)) / 2

    return(center + (c(-1, 1) * (1 + factor * direction)) * halfSize)
}


#' @title Lin
#' @param x0 Where to interpolate.
#' @param x Arguments (size 2).
#' @param y Values (size 2).
#' @return Interpolated value between two provided.
#' @importFrom purrr map_dbl
#' @importFrom magrittr %<>%
#' @export
Lin <- function(x0, x, y) {
    x %<>% unlist %>% as.numeric
    y %<>% unlist %>% as.numeric

    map_dbl(x0, ~ y[1] + diff(y) / diff(x) * (. - x[1]))
}